### ISSUE TITLE
"rippled-ws-client-pool" deprecated

### ISSUE THREAD

**Issue by shortthefomo** [WietseWind/rippled-ws-client-dashboard#14]
I used this project to learn and understand a lot about javascript and objects and how you composed your classes... beautiful stuff!

but im still rather green at javascript, and "rippled-ws-client-pool" has been deprecated by your xrpl-client project.

could you show how that get replaced out here?
currently im trying to figure out how to get around this.....

`import { XrplClient } from "xrpl-client"
^^^^^^

SyntaxError: Cannot use import statement outside a module`

**Comment by WietseWind** [comment]
That's great to hear :D

That syntax only works in Typescript / compiled JS code, if you are using plain JS (e.g. regular `.js` files executed with node) this should work:

```
const { XrplClient} = require('xrpl-client')
```
